// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALLbNZIanMJmMzEpFf4yb6_EV60Owgbys',
    appId: '1:779287472520:web:5b4d2d309a16ff74bc723d',
    messagingSenderId: '779287472520',
    projectId: 'learning-english-app-5f3fe',
    authDomain: 'learning-english-app-5f3fe.firebaseapp.com',
    storageBucket: 'learning-english-app-5f3fe.appspot.com',
    measurementId: 'G-TL5GDS7EQZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHL8W3koZiGQkMUwId-tLJ5s5Lxnwjfek',
    appId: '1:779287472520:android:5d0c9657eae8f00abc723d',
    messagingSenderId: '779287472520',
    projectId: 'learning-english-app-5f3fe',
    storageBucket: 'learning-english-app-5f3fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-wKh4kInTca6wIGJCYQo0WRlwWKttv3Q',
    appId: '1:779287472520:ios:74c26a9e734556e6bc723d',
    messagingSenderId: '779287472520',
    projectId: 'learning-english-app-5f3fe',
    storageBucket: 'learning-english-app-5f3fe.appspot.com',
    iosClientId: '779287472520-hfe68c6elc9gofse6t9tgn27tophl40b.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningEnglishApp',
  );
}
